# Generated by Django 6.0.6 on 2026-07-11 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(db_column='brand_id', primary_key=True, serialize=False, verbose_name='ID бренда')),
                ('brand_name', models.CharField(db_column='brand_name', max_length=150, unique=True, verbose_name='Название бренда')),
                ('brand_country', models.CharField(blank=True, db_column='brand_country', max_length=100, null=True, verbose_name='Страна бренда')),
                ('brand_description', models.TextField(blank=True, db_column='brand_description', null=True, verbose_name='Описание бренда')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False, verbose_name='ID категории')),
                ('category_name', models.CharField(db_column='category_name', max_length=150, unique=True, verbose_name='Название категории')),
                ('category_description', models.TextField(blank=True, db_column='category_description', null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(db_column='product_id', primary_key=True, serialize=False, verbose_name='ID товара')),
                ('product_name', models.CharField(db_column='product_name', max_length=200, verbose_name='Название товара')),
                ('product_description', models.TextField(blank=True, db_column='product_description', null=True, verbose_name='Описание товара')),
                ('purpose', models.CharField(blank=True, db_column='purpose', max_length=200, null=True, verbose_name='Назначение')),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock_quantity', models.IntegerField(db_column='stock_quantity', verbose_name='Количество на складе')),
                ('product_image', models.URLField(blank=True, db_column='product_image', max_length=500, null=True, verbose_name='Изображение товара')),
                ('brand', models.ForeignKey(db_column='brand_brand_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.brand', verbose_name='Бренд')),
                ('product_category', models.ForeignKey(db_column='product_category_category_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.productcategory', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
            },
        ),
    ]
