# Generated by Django 6.0.6 on 2026-07-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False, verbose_name='ID заказа')),
                ('order_date', models.DateTimeField(auto_now_add=True, db_column='order_date', verbose_name='Дата заказа')),
                ('total_amount', models.DecimalField(db_column='total_amount', decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(db_column='order_item_id', primary_key=True, serialize=False, verbose_name='ID позиции заказа')),
                ('product_quantity', models.IntegerField(db_column='product_quantity', verbose_name='Количество товара')),
                ('product_price_at_order', models.DecimalField(db_column='product_price_at_order', decimal_places=2, max_digits=10, verbose_name='Цена товара на момент заказа')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('status_id', models.AutoField(db_column='status_id', primary_key=True, serialize=False, verbose_name='ID статуса')),
                ('status_name', models.CharField(db_column='status_name', max_length=100, unique=True, verbose_name='Название статуса')),
                ('status_description', models.TextField(blank=True, db_column='status_description', null=True, verbose_name='Описание статуса')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
                'db_table': 'order_status',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_id', models.AutoField(db_column='payment_method_id', primary_key=True, serialize=False, verbose_name='ID способа оплаты')),
                ('payment_method_name', models.CharField(db_column='payment_method_name', max_length=100, unique=True, verbose_name='Название способа оплаты')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'db_table': 'payment_method',
            },
        ),
    ]
