# Generated by Django 6.0.6 on 2026-07-11 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(db_column='delivery_address_address_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.deliveryaddress', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='user_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_column='order_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(db_column='product_product_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(db_column='order_status_status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderstatus', verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(db_column='payment_method_payment_method_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.paymentmethod', verbose_name='Способ оплаты'),
        ),
    ]
