# Generated by Django 6.0.6 on 2026-07-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(db_column='cart_id', primary_key=True, serialize=False, verbose_name='ID корзины')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='creation_date', verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='update_date', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(db_column='cart_item_id', primary_key=True, serialize=False, verbose_name='ID позиции корзины')),
                ('product_quantity', models.PositiveIntegerField(db_column='product_quantity', default=1, verbose_name='Количество товара')),
            ],
            options={
                'verbose_name': 'Позиция корзины',
                'verbose_name_plural': 'Позиции корзины',
                'db_table': 'cart_item',
            },
        ),
    ]
