# 1. Получение списка способов оплаты
GET http://localhost:8000/api/payment-methods/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzNDM2OTgxLCJpYXQiOjE3ODM0MzUxODEsImp0aSI6IjI4YjgyOTgwZjg2OTQ1YmZhYTA2ZDVhODk3ZTRlNTBhIiwidXNlcl9pZCI6IjMifQ.-9c2Cb8agaQ1hS6s49sGGVyzhLrlItzfn0g3_aRO9Yg

### 2. Получение списка способов оплаты без аутентификации
GET http://localhost:8000/api/payment-methods/
Content-Type: application/json

### 3. Получение списка статусов заказов
GET http://localhost:8000/api/order-statuses/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzNDM2OTgxLCJpYXQiOjE3ODM0MzUxODEsImp0aSI6IjI4YjgyOTgwZjg2OTQ1YmZhYTA2ZDVhODk3ZTRlNTBhIiwidXNlcl9pZCI6IjMifQ.-9c2Cb8agaQ1hS6s49sGGVyzhLrlItzfn0g3_aRO9Yg