# Generated by Django 6.0.6 on 2026-07-11 07:00

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleOfUser',
            fields=[
                ('role_id', models.AutoField(db_column='role_id', primary_key=True, serialize=False, verbose_name='ID роли')),
                ('role_name', models.CharField(db_column='role_name', max_length=100, unique=True, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
                'db_table': 'role_of_user',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False, verbose_name='ID пользователя')),
                ('first_name', models.CharField(db_column='first_name', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(db_column='last_name', max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(db_column='email', error_messages={'unique': 'Пользователь с таким email уже существует.'}, max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(db_column='phone', max_length=20, null=True, unique=True, verbose_name='Телефон')),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_column='registration_date', verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='Права пользователя')),
                ('role', models.ForeignKey(db_column='role_of_user_role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.roleofuser', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('address_id', models.AutoField(db_column='address_id', primary_key=True, serialize=False, verbose_name='ID адреса')),
                ('city', models.CharField(db_column='city', max_length=100, verbose_name='Город')),
                ('street', models.CharField(db_column='street', max_length=100, verbose_name='Улица')),
                ('house', models.CharField(db_column='house', max_length=20, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, db_column='apartment', max_length=20, null=True, verbose_name='Квартира')),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False, verbose_name='Удален')),
                ('user', models.ForeignKey(db_column='user_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'db_table': 'delivery_address',
            },
        ),
    ]
